name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build k3os
      run: |
        apt update
        apt install -y grep coreutils
	      df -h /* | grep '^[0-9\.]\+G'
        make
